"""empty message

Revision ID: 25574e969491
Revises: 
Create Date: 2020-09-22 20:14:25.959858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25574e969491'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('age_expectancy', sa.Integer(), nullable=True),
    sa.Column('dob', sa.String(length=32), nullable=True),
    sa.Column('subscribe', sa.Boolean(), nullable=True),
    sa.Column('legend_text', sa.Text(), nullable=True),
    sa.Column('goals_text', sa.Text(), nullable=True),
    sa.Column('statistics_text', sa.Text(), nullable=True),
    sa.Column('joined', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('textcontent', sa.Text(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('colors', sa.Text(), nullable=True),
    sa.Column('user_email', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('decade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('textcontent', sa.Text(), nullable=True),
    sa.Column('colors', sa.Text(), nullable=True),
    sa.Column('user_email', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('radio', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('textcontent', sa.Text(), nullable=True),
    sa.Column('colors', sa.Text(), nullable=True),
    sa.Column('user_email', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('textcontent', sa.Text(), nullable=True),
    sa.Column('colors', sa.Text(), nullable=True),
    sa.Column('user_email', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('textcontent', sa.Text(), nullable=True),
    sa.Column('colors', sa.Text(), nullable=True),
    sa.Column('user_email', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('year')
    op.drop_table('week')
    op.drop_table('month')
    op.drop_table('goals')
    op.drop_table('decade')
    op.drop_table('day')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
